# Site settings
title: Colin's Sweet Profile
email: colin@colinday.co
description: > # this means to ignore newlines until "baseurl:"
  Doin stuff
baseurl: "/patchwork-gh-pages-24"
url: "http://halfwolf.github.io"
twitter_username: AllDayCDay
github_username:  halfwolf
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
